version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRESQL_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRESQL_DATABASE}
      - DB_POSTGRESDB_USER=${POSTGRESQL_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRESQL_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=public
      - N8N_DEFAULT_USER_EMAIL=${N8N_USER_EMAIL}
      - N8N_DEFAULT_USER_PASSWORD=${N8N_USER_PASSWORD}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - GENERIC_TIMEZONE=UTC
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_URL}
      - DB_POSTGRESDB_SSL_MODE=require
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false # 🔥 This allows self-signed certs

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local
