version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRESQL_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRESQL_DATABASE}
      - DB_POSTGRESDB_USER=${POSTGRESQL_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRESQL_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_SSL_MODE=require
      - DB_POSTGRESDB_SSL_ENABLE=true
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false # 🔥 This allows self-signed certs
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_METRICS_TRUST_PROXY=true
      - N8N_RUNNERS_ENABLED=true
      # - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      # - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
      - N8N_DEFAULT_USER_EMAIL=${N8N_USER_EMAIL}
      - N8N_DEFAULT_USER_PASSWORD=${N8N_USER_PASSWORD}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - GENERIC_TIMEZONE=UTC
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - VUE_APP_URL_BASE_API=${WEBHOOK_URL}

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local
